### ISSUE TITLE
Quest - The balance of nature

### ISSUE THREAD

**Issue by LightningBlade** [cybrann/MistsOfPandaria-IssueTracker#9]
QUEST: http://www.wowhead.com/quest=28713/the-balance-of-nature
    NPC  : http://www.wowhead.com/npc=2031/young-nightsaber
    Issue: The Nightsabers do NOT move in their supposed/intended behaviour, however, it does not impact the ability to complete the quest in any way.
    Screenshot: https://puu.sh/ujeq3/0d0015ad13.jpg

**Comment by BlackMetalz** [comment]
Fixed next update!

**Comment by LightningBlade** [comment]
Awesome, closing it then
